### ISSUE TITLE
Checking to make sure a file is selected

### ISSUE THREAD

**Issue by oussamabonnor1** [imadtoubal/Pytorch-Flask-Starter#4]
An unhandeled exception it thrown when the upload button is clicked without selecting a file to upload, it's not a big deal but it would be nice to fix! Maybe disable the button unless a file is selected.

**Comment by imadtoubal** [comment]
Thank you @oussamabonnor1, I fixed it by adding a "required" attribute to the file input. (Handled in the front end)
